language: generic

sudo: required

if: tag IS present

addons:
  apt:
    packages:
       - wget
       - make
       - libncurses-dev
       - flex
       - bison
       - gperf
       - python
       - python-serial
       - build-essential
       - libreadline-dev
       - libffi-dev
       - pkg-config

script: bash scripts/build.sh


deploy:
  provider: script
  script: bash scripts/deploy.sh
