language: generic

sudo: required

on:
  tags: true

addons:
  apt:
    packages:
       - wget
       - make
       - libncurses-dev
       - flex
       - bison
       - gperf
       - python
       - python-serial
       - build-essential
       - libreadline-dev
       - libffi-dev
       - pkg-config

script: bash scripts/build.sh

